import 'json.dart';

// What Wisp reads: the three book analyses, the reverse outline at its three
// lengths, and the continuity report. All of them are written by server jobs
// and read back from their caches; none is generated by a read.

enum AnalysisId {
  theme,
  pacing,
  genre;

  /// The job's `analysis` param and the route segment.
  String get wire => name;
}

class ThemeEntry {
  const ThemeEntry({
    required this.name,
    required this.statement,
    required this.howItWorks,
    required this.development,
    required this.chapters,
  });
  final String name;
  final String statement;
  final String howItWorks;
  final String development;
  final List<String> chapters;

  static ThemeEntry fromJson(Json json) => ThemeEntry(
        name: asString(json['name']),
        statement: asString(json['statement']),
        howItWorks: asString(json['how_it_works']),
        development: asString(json['development']),
        chapters: asStringList(json['chapters']),
      );
}

/// One chapter's place on the pacing wave: 0 a lull, 10 peak tension.
class PacingBeat {
  const PacingBeat({required this.chapter, required this.intensity, required this.note});
  final String chapter;
  final double intensity;
  final String note;

  static PacingBeat fromJson(Json json) => PacingBeat(
        chapter: asString(json['chapter']),
        intensity: asDouble(json['intensity']).clamp(0, 10).toDouble(),
        note: asString(json['note']),
      );
}

class PacingStretch {
  const PacingStretch({required this.from, required this.to, required this.shape, required this.description});
  final String from;
  final String to;
  final String shape;
  final String description;

  static PacingStretch fromJson(Json json) => PacingStretch(
        from: asString(json['from']),
        to: asString(json['to']),
        shape: asString(json['shape']),
        description: asString(json['description']),
      );
}

enum ExpectationStatus {
  met,
  subverted,
  notAddressed;

  static ExpectationStatus fromWire(String value) => switch (value) {
        'met' => met,
        'subverted' => subverted,
        _ => notAddressed,
      };
}

class GenreExpectation {
  const GenreExpectation({required this.expectation, required this.status, required this.how});
  final String expectation;
  final ExpectationStatus status;
  final String how;

  static GenreExpectation fromJson(Json json) => GenreExpectation(
        expectation: asString(json['expectation']),
        status: ExpectationStatus.fromWire(asString(json['status'])),
        how: asString(json['how']),
      );
}

class GenreEntry {
  const GenreEntry({required this.name, required this.primary, required this.why, required this.expectations});
  final String name;
  final bool primary;
  final String why;
  final List<GenreExpectation> expectations;

  static GenreEntry fromJson(Json json) => GenreEntry(
        name: asString(json['name']),
        primary: json['role'] == 'primary',
        why: asString(json['why']),
        expectations: asJsonList(json['expectations']).map(GenreExpectation.fromJson).toList(),
      );
}

/// One book analysis. Which of `themes`, `beats`/`stretches` or `genres` is
/// filled is `analysis`; the others come back empty.
class AnalysisReport {
  const AnalysisReport({
    required this.analysis,
    required this.generatedAt,
    required this.chapterCount,
    required this.overview,
    required this.themes,
    required this.beats,
    required this.stretches,
    required this.genres,
  });
  final String analysis;
  final String generatedAt;
  final int chapterCount;
  final String overview;
  final List<ThemeEntry> themes;
  final List<PacingBeat> beats;
  final List<PacingStretch> stretches;
  final List<GenreEntry> genres;

  static AnalysisReport fromJson(Json json) => AnalysisReport(
        analysis: asString(json['analysis']),
        generatedAt: asString(json['generated_at']),
        chapterCount: asInt(json['chapter_count']),
        overview: asString(json['overview']),
        themes: asJsonList(json['themes']).map(ThemeEntry.fromJson).toList(),
        beats: asJsonList(json['beats']).map(PacingBeat.fromJson).toList(),
        stretches: asJsonList(json['stretches']).map(PacingStretch.fromJson).toList(),
        genres: asJsonList(json['genres']).map(GenreEntry.fromJson).toList(),
      );
}

enum OutlineLength {
  synopsis,
  extended,
  detailed;

  String get wire => name;
}

/// One chapter of the detailed reverse outline. The entry carries more
/// (POV, interior track, relational beat); the page reads only these.
class ChapterOutline {
  const ChapterOutline({required this.chapter, required this.summary, required this.wordCount});
  final String chapter;
  final String summary;
  final int? wordCount;

  static ChapterOutline fromJson(Json json) => ChapterOutline(
        chapter: asString(json['chapter']),
        summary: asString(json['summary']),
        wordCount: json['word_count'] is num ? asInt(json['word_count']) : null,
      );
}

enum OutlineBeat {
  setup('Setup'),
  incitingEvent('Inciting event'),
  complication('Complication'),
  crisis('Crisis'),
  climax('Climax'),
  resolution('Resolution');

  const OutlineBeat(this.label);
  final String label;

  static OutlineBeat fromWire(String value) => switch (value) {
        'inciting_event' => incitingEvent,
        'complication' => complication,
        'crisis' => crisis,
        'climax' => climax,
        'resolution' => resolution,
        _ => setup,
      };
}

/// A synopsis or extended outline: prose in six movements, in order. A
/// section's text is paragraphs separated by a blank line.
class CondensedOutline {
  const CondensedOutline({required this.wordCount, required this.sections});
  final int wordCount;
  final List<({OutlineBeat beat, String text})> sections;

  static CondensedOutline fromJson(Json json) => CondensedOutline(
        wordCount: asInt(json['word_count']),
        sections: asJsonList(json['sections'])
            .map((s) => (beat: OutlineBeat.fromWire(asString(s['beat'])), text: asString(s['text'])))
            .toList(),
      );
}

/// Every length of the reverse outline, from the one cache row. `chapters`
/// is empty when the book has never been outlined.
class OutlineResult {
  const OutlineResult({required this.chapters, required this.synopsis, required this.extended});
  final List<ChapterOutline> chapters;
  final CondensedOutline? synopsis;
  final CondensedOutline? extended;

  static const empty = OutlineResult(chapters: [], synopsis: null, extended: null);

  CondensedOutline? condensed(OutlineLength length) => switch (length) {
        OutlineLength.synopsis => synopsis,
        OutlineLength.extended => extended,
        OutlineLength.detailed => null,
      };

  static OutlineResult fromJson(Json json) => OutlineResult(
        chapters: asJsonList(json['outline']).map(ChapterOutline.fromJson).toList(),
        synopsis: json['synopsis'] is Map ? CondensedOutline.fromJson(asJson(json['synopsis'])) : null,
        extended: json['extended'] is Map ? CondensedOutline.fromJson(asJson(json['extended'])) : null,
      );
}

/// How the author ruled on a finding: `prior` — the earlier chapter is
/// right; `current` — the newer one is; `intentional` — a deliberate change.
class ContinuityResolution {
  const ContinuityResolution({required this.choice, required this.note});
  final String choice;
  final String? note;

  static ContinuityResolution fromJson(Json json) =>
      ContinuityResolution(choice: asString(json['choice']), note: json['note'] as String?);
}

/// One finding. Every field but `chapter` is advisory on the wire, so each
/// is read defensively.
class ContinuityFinding {
  const ContinuityFinding({
    required this.hardError,
    required this.category,
    required this.entity,
    required this.chapter,
    required this.quote,
    required this.priorChapter,
    required this.priorQuote,
    required this.claim,
    required this.explanation,
    required this.verified,
    required this.resolution,
  });
  final bool hardError;
  final String category;
  final String? entity;
  final String chapter;
  final String? quote;
  final String? priorChapter;
  final String? priorQuote;
  final String? claim;
  final String? explanation;
  final bool verified;
  final ContinuityResolution? resolution;

  static String? _text(dynamic value) => value is String && value.trim().isNotEmpty ? value : null;

  static ContinuityFinding fromJson(Json json) => ContinuityFinding(
        hardError: json['kind'] != 'arc_drift',
        category: asString(json['category']),
        entity: _text(json['entity']),
        chapter: asString(json['chapter']),
        quote: _text(json['quote']),
        priorChapter: _text(json['prior_chapter']),
        priorQuote: _text(json['prior_quote']),
        claim: _text(json['claim']),
        explanation: _text(json['explanation']) ?? _text(json['why_not_development']),
        verified: asBool(json['verified'], true),
        resolution: json['resolution'] is Map ? ContinuityResolution.fromJson(asJson(json['resolution'])) : null,
      );
}

class ContinuityReport {
  const ContinuityReport({
    required this.chaptersAnalyzed,
    required this.hardErrors,
    required this.arcDrift,
    required this.claimsExtracted,
    required this.candidates,
    required this.dismissed,
    required this.extractionFailures,
  });
  final int chaptersAnalyzed;
  final List<ContinuityFinding> hardErrors;
  final List<ContinuityFinding> arcDrift;
  final int claimsExtracted;
  final int candidates;
  final int dismissed;
  final List<String> extractionFailures;

  static ContinuityReport fromJson(Json json) {
    final stats = json['stats'] is Map ? asJson(json['stats']) : const <String, dynamic>{};
    return ContinuityReport(
      chaptersAnalyzed: asInt(json['chapters_analyzed']),
      hardErrors: asJsonList(json['hard_errors']).map(ContinuityFinding.fromJson).toList(),
      arcDrift: asJsonList(json['arc_drift']).map(ContinuityFinding.fromJson).toList(),
      claimsExtracted: asInt(stats['claims_extracted']),
      candidates: asInt(stats['candidates']),
      dismissed: asInt(stats['dismissed']),
      extractionFailures: asStringList(stats['extraction_failures']),
    );
  }
}
