import 'jobs.dart';
import 'json.dart';

// What Wisp reads: the three book analyses, the beta readers' letters, the
// reverse outline at its three lengths, and the continuity report. All of
// them are written by server jobs and read back from their caches; none is
// generated by a read.

/// The three analyses with a page of their own. A beta reader's letter is a
/// book analysis too (`beta_<cat>`), but the readers are the server's list
/// (GET /beta-readers), so their ids travel as the wire string the catalogue
/// sent — the reads and runs below take any analysis id as a string.
enum AnalysisId {
  theme,
  pacing,
  genre;

  /// The job's `analysis` param and the route segment.
  String get wire => name;
}

/// One beta reader as the catalogue sends them: the cat, their shelf, and
/// whether this book's letter from them is stored. Never the letter itself.
class ReaderCard {
  const ReaderCard({
    required this.id,
    required this.analysis,
    required this.name,
    required this.genres,
    required this.description,
    required this.picture,
    required this.hasLetter,
  });
  final String id;

  /// The analysis id the letter is read and run under: `beta_<cat>`.
  final String analysis;
  final String name;
  final String genres;
  final String description;

  /// The cat as a self-contained SVG document.
  final String picture;
  final bool hasLetter;

  static ReaderCard fromJson(Json json) => ReaderCard(
        id: asString(json['id']),
        analysis: asString(json['analysis']),
        name: asString(json['name']),
        genres: asString(json['genres']),
        description: asString(json['description']),
        picture: asString(json['picture']),
        hasLetter: asBool(json['has_letter']),
      );

  static List<ReaderCard> listFromJson(Json json) => asJsonList(json['readers']).map(ReaderCard.fromJson).toList();
}

/// What a beta reader felt at a moment of the book.
enum BetaReaction {
  hooked,
  delighted,
  moved,
  laughed,
  surprised,
  guessed,
  confused,
  drifted;

  static BetaReaction fromWire(String value) => values.where((r) => r.name == value).firstOrNull ?? hooked;
}

/// One of the reader's own questions, answered, with the passages it leans on.
class BetaAnswer {
  const BetaAnswer({required this.question, required this.answer, required this.quotes});
  final String question;
  final String answer;
  final List<String> quotes;

  static BetaAnswer fromJson(Json json) => BetaAnswer(
        question: asString(json['question']),
        answer: asString(json['answer']),
        quotes: asStringList(json['quotes']),
      );
}

/// One of the reader's comments in the margin, pinned to a passage of its
/// chapter (`quote`) or, with none, to the chapter as a whole.
class BetaComment {
  const BetaComment({required this.chapter, required this.reaction, required this.note, required this.quote});
  final String chapter;
  final BetaReaction reaction;
  final String note;
  final String? quote;

  static BetaComment fromJson(Json json) => BetaComment(
        chapter: asString(json['chapter']),
        reaction: BetaReaction.fromWire(asString(json['reaction'])),
        note: asString(json['note']),
        quote: json['quote'] is String && (json['quote'] as String).trim().isNotEmpty ? json['quote'] as String : null,
      );
}

/// What a block of a book page is: a heading, a paragraph, or a scene break.
enum PageBlockKind {
  heading,
  paragraph,
  sceneBreak;

  static PageBlockKind fromWire(String value) => switch (value) {
        'heading' => heading,
        'break' => sceneBreak,
        _ => paragraph,
      };
}

/// One block of a book page, as plain text (the markdown's emphasis taken
/// out; empty for a scene break).
class PageBlock {
  const PageBlock({required this.kind, required this.text, this.continued = false});
  final PageBlockKind kind;
  final String text;

  /// A paragraph that began on the page before — drawn without an indent.
  final bool continued;

  static PageBlock fromJson(Json json) => PageBlock(
        kind: PageBlockKind.fromWire(asString(json['kind'])),
        text: asString(json['text']),
        continued: asBool(json['continued']),
      );
}

/// One page of the book, about 300 words, cut by the server. A chapter
/// always starts a page; a long paragraph runs on to the next one.
class BookPage {
  const BookPage({required this.chapter, required this.blocks});
  final String chapter;
  final List<PageBlock> blocks;

  static BookPage fromJson(Json json) => BookPage(
        chapter: asString(json['chapter']),
        blocks: asJsonList(json['blocks']).map(PageBlock.fromJson).toList(),
      );
}

/// Where a comment's passage sits on its page: block [block] of it, and the
/// span [from]..[to] of that block's text (UTF-16 offsets, as Dart indexes).
typedef CommentSpan = ({int block, int from, int to});

/// A comment placed on the page that holds its passage.
class PlacedBetaComment extends BetaComment {
  const PlacedBetaComment({
    required super.chapter,
    required super.reaction,
    required super.note,
    required super.quote,
    required this.page,
    required this.at,
  });

  /// Index into the book's `pages`.
  final int page;

  /// Null when the comment is about its chapter, or its passage has since
  /// been rewritten — it then sits on the chapter's first page.
  final CommentSpan? at;

  static PlacedBetaComment fromJson(Json json) {
    final base = BetaComment.fromJson(json);
    final at = json['at'];
    return PlacedBetaComment(
      chapter: base.chapter,
      reaction: base.reaction,
      note: base.note,
      quote: base.quote,
      page: asInt(json['page']),
      at: at is Map
          ? (block: asInt(at['block']), from: asInt(at['from']), to: asInt(at['to']))
          : null,
    );
  }
}

/// The chapters a reader read, as pages, with their comments pinned on.
class CommentedBook {
  const CommentedBook({required this.pages, required this.comments, required this.unplaced});
  final List<BookPage> pages;

  /// In reading order — by page, then by where on the page.
  final List<PlacedBetaComment> comments;

  /// Comments on chapters no longer in the book.
  final int unplaced;

  static CommentedBook fromJson(Json json) => CommentedBook(
        pages: asJsonList(json['pages']).map(BookPage.fromJson).toList(),
        comments: asJsonList(json['comments']).map(PlacedBetaComment.fromJson).toList(),
        unplaced: asInt(json['unplaced']),
      );
}

/// GET /beta-readers/{reader}/pages: the book, null when that reader hasn't
/// read it, and how many comments a preview held back.
class BetaReaderPages {
  const BetaReaderPages({required this.book, required this.hiddenComments});
  final CommentedBook? book;
  final int hiddenComments;

  static BetaReaderPages fromJson(Json json) => BetaReaderPages(
        book: json['book'] is Map ? CommentedBook.fromJson(asJson(json['book'])) : null,
        hiddenComments: asInt(json['hidden_comments']),
      );
}

/// Where the reader would have stopped reading.
class BetaPutDown {
  const BetaPutDown({required this.chapter, required this.why});
  final String chapter;
  final String why;

  static BetaPutDown? fromJson(dynamic value) {
    if (value is! Map) return null;
    final json = asJson(value);
    final (chapter, why) = (asString(json['chapter']), asString(json['why']));
    return chapter.isEmpty && why.isEmpty ? null : BetaPutDown(chapter: chapter, why: why);
  }
}

class ThemeEntry {
  const ThemeEntry({
    required this.name,
    required this.statement,
    required this.howItWorks,
    required this.development,
    required this.further,
    required this.chapters,
  });
  final String name;
  final String statement;
  final String howItWorks;
  final String development;

  /// Ways to take the theme further; empty on reports written before 2026-09-26.
  final List<String> further;
  final List<String> chapters;

  static ThemeEntry fromJson(Json json) => ThemeEntry(
        name: asString(json['name']),
        statement: asString(json['statement']),
        howItWorks: asString(json['how_it_works']),
        development: asString(json['development']),
        further: asStringList(json['further']),
        chapters: asStringList(json['chapters']),
      );
}

/// One chapter's place on the pacing wave: 0 a lull, 10 peak tension.
class PacingBeat {
  const PacingBeat({required this.chapter, required this.intensity, required this.note});
  final String chapter;
  final double intensity;
  final String note;

  static PacingBeat fromJson(Json json) => PacingBeat(
        chapter: asString(json['chapter']),
        intensity: asDouble(json['intensity']).clamp(0, 10).toDouble(),
        note: asString(json['note']),
      );
}

/// One of a pacing report's three to five acts, read like the book.
class PacingAct {
  const PacingAct({
    required this.name,
    required this.from,
    required this.to,
    required this.summary,
    required this.reading,
  });
  final String name;
  final String from;
  final String to;

  /// How the act holds the reader.
  final String summary;
  final PacingReading reading;

  static PacingAct fromJson(Json json) => PacingAct(
        name: asString(json['name']),
        from: asString(json['from']),
        to: asString(json['to']),
        summary: asString(json['summary']),
        reading: PacingReading.fromJson(json),
      );
}

/// What the book (or the chapters picked) and each act are read for: how
/// soon the reader is caught, how soon the tension climbs, whether the ending
/// grows out of the main plot, and how to keep the reader engaged.
class PacingReading {
  const PacingReading({required this.hook, required this.rise, required this.resolution, required this.tips});
  final PacingMilestone? hook;
  final PacingMilestone? rise;
  final PacingResolution? resolution;
  final List<String> tips;

  bool get isEmpty => hook == null && rise == null && resolution == null && tips.isEmpty;

  static PacingReading fromJson(Json json) => PacingReading(
        hook: PacingMilestone.fromJson(json['hook']),
        rise: PacingMilestone.fromJson(json['rise']),
        resolution: PacingResolution.fromJson(json['resolution']),
        tips: asStringList(json['tips']),
      );
}

enum PacingPace {
  quick,
  steady,
  slow;

  static PacingPace fromWire(String value) => switch (value) {
        'quick' => quick,
        'slow' => slow,
        _ => steady,
      };
}

/// Where the reader is caught (`hook`) or the tension starts climbing
/// (`rise`), and how far into its scope (the book, or one act) that is.
class PacingMilestone {
  const PacingMilestone({
    required this.chapter,
    required this.wordsIn,
    required this.share,
    required this.pace,
    required this.reading,
  });
  final String chapter;

  /// Words read by the end of [chapter]; null when a count was missing.
  final int? wordsIn;

  /// The same as a share of the chapters read, 0–1.
  final double? share;
  final PacingPace pace;
  final String reading;

  static PacingMilestone? fromJson(dynamic value) {
    if (value is! Map) return null;
    final json = asJson(value);
    return PacingMilestone(
      chapter: asString(json['chapter']),
      wordsIn: json['words_in'] is num ? asInt(json['words_in']) : null,
      share: json['share'] is num ? asDouble(json['share']) : null,
      pace: PacingPace.fromWire(asString(json['pace'])),
      reading: asString(json['reading']),
    );
  }
}

enum PacingConnection {
  tight,
  partial,
  loose;

  static PacingConnection fromWire(String value) => switch (value) {
        'tight' => tight,
        'loose' => loose,
        _ => partial,
      };
}

/// Whether the ending is tightly connected to the main plot.
class PacingResolution {
  const PacingResolution({required this.connection, required this.reading, required this.looseEnds});
  final PacingConnection connection;
  final String reading;
  final List<String> looseEnds;

  static PacingResolution? fromJson(dynamic value) {
    if (value is! Map) return null;
    final json = asJson(value);
    return PacingResolution(
      connection: PacingConnection.fromWire(asString(json['connection'])),
      reading: asString(json['reading']),
      looseEnds: asStringList(json['loose_ends']),
    );
  }
}

enum ExpectationStatus {
  met,
  subverted,
  notAddressed;

  static ExpectationStatus fromWire(String value) => switch (value) {
        'met' => met,
        'subverted' => subverted,
        _ => notAddressed,
      };
}

class GenreExpectation {
  const GenreExpectation({required this.expectation, required this.status, required this.how});
  final String expectation;
  final ExpectationStatus status;
  final String how;

  static GenreExpectation fromJson(Json json) => GenreExpectation(
        expectation: asString(json['expectation']),
        status: ExpectationStatus.fromWire(asString(json['status'])),
        how: asString(json['how']),
      );
}

class GenreEntry {
  const GenreEntry({required this.name, required this.primary, required this.why, required this.expectations});
  final String name;
  final bool primary;
  final String why;
  final List<GenreExpectation> expectations;

  static GenreEntry fromJson(Json json) => GenreEntry(
        name: asString(json['name']),
        primary: json['role'] == 'primary',
        why: asString(json['why']),
        expectations: asJsonList(json['expectations']).map(GenreExpectation.fromJson).toList(),
      );
}

/// One book analysis. Which of `themes`, the pacing fields (`beats`,
/// `reading`, `acts`), `genres` or the beta read's (`reader`, `letter`,
/// `answers`, `chapters`, `comments`, `putDown`) is filled is `analysis`; the others come
/// back empty. A beta read carries no `overview`.
class AnalysisReport {
  const AnalysisReport({
    required this.analysis,
    required this.generatedAt,
    required this.chapterCount,
    required this.ranged,
    required this.overview,
    required this.themes,
    required this.beats,
    required this.reading,
    required this.acts,
    required this.genres,
    this.reader = '',
    this.letter = '',
    this.answers = const [],
    this.chapters = const [],
    this.comments = const [],
    this.putDown,
  });
  final String analysis;
  final String generatedAt;
  final int chapterCount;

  /// Read over a range of chapters rather than the whole book.
  final bool ranged;
  final String overview;
  final List<ThemeEntry> themes;
  final List<PacingBeat> beats;
  /// Pacing: the book (or the chapters picked) read for engagement.
  final PacingReading reading;

  /// Pacing: each act read the same way; empty on a range.
  final List<PacingAct> acts;
  final List<GenreEntry> genres;

  /// Beta read: the cat who read it.
  final String reader;

  /// Beta read: the letter, paragraphs split by blank lines. The first is the
  /// whole reaction, and all a preview keeps.
  final String letter;
  final List<BetaAnswer> answers;

  /// Beta read: the chapters read, in order.
  final List<String> chapters;

  /// Beta read: the comments in the margin, in reading order. A preview keeps
  /// only the first; the book they sit on is GET /beta-readers/{reader}/pages.
  final List<BetaComment> comments;

  /// Beta read: where they'd have stopped; null when they never would have.
  final BetaPutDown? putDown;

  List<String> get letterParagraphs =>
      letter.split(RegExp(r'\n\s*\n')).map((p) => p.trim()).where((p) => p.isNotEmpty).toList();

  static AnalysisReport fromJson(Json json) => AnalysisReport(
        analysis: asString(json['analysis']),
        generatedAt: asString(json['generated_at']),
        chapterCount: asInt(json['chapter_count']),
        ranged: json['range'] is Map,
        overview: asString(json['overview']),
        themes: asJsonList(json['themes']).map(ThemeEntry.fromJson).toList(),
        beats: asJsonList(json['beats']).map(PacingBeat.fromJson).toList(),
        reading: PacingReading.fromJson(json),
        acts: asJsonList(json['acts']).map(PacingAct.fromJson).toList(),
        genres: asJsonList(json['genres']).map(GenreEntry.fromJson).toList(),
        reader: asString(json['reader']),
        letter: asString(json['letter']),
        answers: asJsonList(json['answers']).map(BetaAnswer.fromJson).toList(),
        chapters: asStringList(json['chapters']),
        comments: asJsonList(json['comments']).map(BetaComment.fromJson).toList(),
        putDown: BetaPutDown.fromJson(json['put_down']),
      );
}

/// A report the plan reads as a preview: how much of it the server held back
/// (`lib/wisp/preview.ts`), so the page can draw a blur that size without
/// ever being sent the rest. `hiddenUnits` counts blocks — chapters for the
/// detailed outline, paragraphs for condensed prose, paragraphs and sections
/// for an analysis.
class PreviewCut {
  const PreviewCut({required this.hiddenWords, required this.hiddenUnits});
  final int hiddenWords;
  final int hiddenUnits;

  static PreviewCut? fromJson(dynamic value) {
    if (value is! Map) return null;
    final json = asJson(value);
    return PreviewCut(hiddenWords: asInt(json['hidden_words']), hiddenUnits: asInt(json['hidden_units']));
  }
}

/// One analysis as the read returns it: the report (null before a first
/// run) and, below `wisp.full_reports`, how much of it was held back.
class AnalysisRead {
  const AnalysisRead({required this.report, required this.preview});
  final AnalysisReport? report;
  final PreviewCut? preview;

  static AnalysisRead fromJson(Json json) => AnalysisRead(
        report: json['report'] is Map ? AnalysisReport.fromJson(asJson(json['report'])) : null,
        preview: PreviewCut.fromJson(json['preview']),
      );
}

enum OutlineLength {
  synopsis,
  extended,
  detailed;

  String get wire => name;
}

/// One chapter of the detailed reverse outline. The entry carries more
/// (POV, interior track, relational beat); the page reads only these.
class ChapterOutline {
  const ChapterOutline({required this.chapter, required this.summary, required this.wordCount});
  final String chapter;
  final String summary;
  final int? wordCount;

  static ChapterOutline fromJson(Json json) => ChapterOutline(
        chapter: asString(json['chapter']),
        summary: asString(json['summary']),
        wordCount: json['word_count'] is num ? asInt(json['word_count']) : null,
      );
}

/// A synopsis or extended outline: continuous prose, setup to resolution,
/// with no section headers. [text] is paragraphs separated by a blank line.
class CondensedOutline {
  const CondensedOutline({required this.wordCount, required this.text});
  final int wordCount;
  final String text;

  static CondensedOutline fromJson(Json json) => CondensedOutline(
        wordCount: asInt(json['word_count']),
        text: asString(json['text']),
      );
}

/// Every length of the reverse outline, from the one cache row. `chapters`
/// is empty when the book has never been outlined.
///
/// `previews` is per length what a plan below `wisp.full_reports` did not
/// get of it; empty when the whole outline was read.
class OutlineResult {
  const OutlineResult({
    required this.chapters,
    required this.synopsis,
    required this.extended,
    this.previews = const {},
  });
  final List<ChapterOutline> chapters;
  final CondensedOutline? synopsis;
  final CondensedOutline? extended;
  final Map<OutlineLength, PreviewCut> previews;

  static const empty = OutlineResult(chapters: [], synopsis: null, extended: null);

  CondensedOutline? condensed(OutlineLength length) => switch (length) {
        OutlineLength.synopsis => synopsis,
        OutlineLength.extended => extended,
        OutlineLength.detailed => null,
      };

  static OutlineResult fromJson(Json json) {
    final preview = json['preview'] is Map ? asJson(json['preview']) : const <String, dynamic>{};
    return OutlineResult(
      chapters: asJsonList(json['outline']).map(ChapterOutline.fromJson).toList(),
      synopsis: json['synopsis'] is Map ? CondensedOutline.fromJson(asJson(json['synopsis'])) : null,
      extended: json['extended'] is Map ? CondensedOutline.fromJson(asJson(json['extended'])) : null,
      previews: {
        for (final (length, key) in [
          (OutlineLength.detailed, 'outline'),
          (OutlineLength.synopsis, 'synopsis'),
          (OutlineLength.extended, 'extended'),
        ])
          length: ?PreviewCut.fromJson(preview[key]),
      },
    );
  }
}

/// How the author ruled on a finding: `prior` — the earlier chapter is
/// right; `current` — the newer one is; `intentional` — a deliberate change.
class ContinuityResolution {
  const ContinuityResolution({required this.choice, required this.note});
  final String choice;
  final String? note;

  static ContinuityResolution fromJson(Json json) =>
      ContinuityResolution(choice: asString(json['choice']), note: json['note'] as String?);
}

/// One finding. Every field but `chapter` is advisory on the wire, so each
/// is read defensively.
///
/// `question` is the "which is the story?" still waiting on the author — set
/// on a hard error with no resolution, absent once it is answered (or when
/// the finding was never verified). The report is where it can always be
/// answered: closing its job panel card only stops the job feed carrying it.
class ContinuityFinding {
  const ContinuityFinding({
    required this.hardError,
    required this.category,
    required this.entity,
    required this.chapter,
    required this.quote,
    required this.priorChapter,
    required this.priorQuote,
    required this.claim,
    required this.explanation,
    required this.verified,
    required this.resolution,
    this.question,
  });
  final bool hardError;
  final String category;
  final String? entity;
  final String chapter;
  final String? quote;
  final String? priorChapter;
  final String? priorQuote;
  final String? claim;
  final String? explanation;
  final bool verified;
  final ContinuityResolution? resolution;
  final JobQuestion? question;

  static String? _text(dynamic value) => value is String && value.trim().isNotEmpty ? value : null;

  static ContinuityFinding fromJson(Json json) => ContinuityFinding(
        hardError: json['kind'] != 'arc_drift',
        category: asString(json['category']),
        entity: _text(json['entity']),
        chapter: asString(json['chapter']),
        quote: _text(json['quote']),
        priorChapter: _text(json['prior_chapter']),
        priorQuote: _text(json['prior_quote']),
        claim: _text(json['claim']),
        explanation: _text(json['explanation']) ?? _text(json['why_not_development']),
        verified: asBool(json['verified'], true),
        resolution: json['resolution'] is Map ? ContinuityResolution.fromJson(asJson(json['resolution'])) : null,
        question: json['question'] is Map ? JobQuestion.fromJson(asJson(json['question'])) : null,
      );
}

class ContinuityReport {
  const ContinuityReport({
    required this.chaptersAnalyzed,
    required this.hardErrors,
    required this.arcDrift,
    required this.claimsExtracted,
    required this.candidates,
    required this.dismissed,
    required this.extractionFailures,
  });
  final int chaptersAnalyzed;
  final List<ContinuityFinding> hardErrors;
  final List<ContinuityFinding> arcDrift;
  final int claimsExtracted;
  final int candidates;
  final int dismissed;
  final List<String> extractionFailures;

  int get findingCount => hardErrors.length + arcDrift.length;

  static ContinuityReport fromJson(Json json) {
    final stats = json['stats'] is Map ? asJson(json['stats']) : const <String, dynamic>{};
    return ContinuityReport(
      chaptersAnalyzed: asInt(json['chapters_analyzed']),
      hardErrors: asJsonList(json['hard_errors']).map(ContinuityFinding.fromJson).toList(),
      arcDrift: asJsonList(json['arc_drift']).map(ContinuityFinding.fromJson).toList(),
      claimsExtracted: asInt(stats['claims_extracted']),
      candidates: asInt(stats['candidates']),
      dismissed: asInt(stats['dismissed']),
      extractionFailures: asStringList(stats['extraction_failures']),
    );
  }
}

/// The plot-hole report as the read returns it: the report (null before a
/// first run) and, below `wisp.full_reports`, how much of it was held back.
/// A preview's report carries one finding — the first hard error in chapter
/// order, else the first arc drift — with `stats` whole; `hiddenUnits` counts
/// the findings held back.
class ContinuityRead {
  const ContinuityRead({required this.report, required this.preview});
  final ContinuityReport? report;
  final PreviewCut? preview;

  /// Every finding the report found, shown or held back.
  int get issueCount => (report?.findingCount ?? 0) + (preview?.hiddenUnits ?? 0);

  static ContinuityRead fromJson(Json json) => ContinuityRead(
        report: json['report'] is Map ? ContinuityReport.fromJson(asJson(json['report'])) : null,
        preview: PreviewCut.fromJson(json['preview']),
      );
}
