import 'json.dart';

// What Wisp reads: the three book analyses, the reverse outline at its three
// lengths, and the continuity report. All of them are written by server jobs
// and read back from their caches; none is generated by a read.

enum AnalysisId {
  theme,
  pacing,
  genre;

  /// The job's `analysis` param and the route segment.
  String get wire => name;
}

class ThemeEntry {
  const ThemeEntry({
    required this.name,
    required this.statement,
    required this.howItWorks,
    required this.development,
    required this.further,
    required this.chapters,
  });
  final String name;
  final String statement;
  final String howItWorks;
  final String development;

  /// Ways to take the theme further; empty on reports written before 2026-09-26.
  final List<String> further;
  final List<String> chapters;

  static ThemeEntry fromJson(Json json) => ThemeEntry(
        name: asString(json['name']),
        statement: asString(json['statement']),
        howItWorks: asString(json['how_it_works']),
        development: asString(json['development']),
        further: asStringList(json['further']),
        chapters: asStringList(json['chapters']),
      );
}

/// One chapter's place on the pacing wave: 0 a lull, 10 peak tension.
class PacingBeat {
  const PacingBeat({required this.chapter, required this.intensity, required this.note});
  final String chapter;
  final double intensity;
  final String note;

  static PacingBeat fromJson(Json json) => PacingBeat(
        chapter: asString(json['chapter']),
        intensity: asDouble(json['intensity']).clamp(0, 10).toDouble(),
        note: asString(json['note']),
      );
}

/// One of a pacing report's three to five acts, read like the book.
class PacingAct {
  const PacingAct({
    required this.name,
    required this.from,
    required this.to,
    required this.summary,
    required this.reading,
  });
  final String name;
  final String from;
  final String to;

  /// How the act holds the reader.
  final String summary;
  final PacingReading reading;

  static PacingAct fromJson(Json json) => PacingAct(
        name: asString(json['name']),
        from: asString(json['from']),
        to: asString(json['to']),
        summary: asString(json['summary']),
        reading: PacingReading.fromJson(json),
      );
}

/// What the book (or the chapters picked) and each act are read for: how
/// soon the reader is caught, how soon the tension climbs, whether the ending
/// grows out of the main plot, and how to keep the reader engaged.
class PacingReading {
  const PacingReading({required this.hook, required this.rise, required this.resolution, required this.tips});
  final PacingMilestone? hook;
  final PacingMilestone? rise;
  final PacingResolution? resolution;
  final List<String> tips;

  bool get isEmpty => hook == null && rise == null && resolution == null && tips.isEmpty;

  static PacingReading fromJson(Json json) => PacingReading(
        hook: PacingMilestone.fromJson(json['hook']),
        rise: PacingMilestone.fromJson(json['rise']),
        resolution: PacingResolution.fromJson(json['resolution']),
        tips: asStringList(json['tips']),
      );
}

enum PacingPace {
  quick,
  steady,
  slow;

  static PacingPace fromWire(String value) => switch (value) {
        'quick' => quick,
        'slow' => slow,
        _ => steady,
      };
}

/// Where the reader is caught (`hook`) or the tension starts climbing
/// (`rise`), and how far into its scope (the book, or one act) that is.
class PacingMilestone {
  const PacingMilestone({
    required this.chapter,
    required this.wordsIn,
    required this.share,
    required this.pace,
    required this.reading,
  });
  final String chapter;

  /// Words read by the end of [chapter]; null when a count was missing.
  final int? wordsIn;

  /// The same as a share of the chapters read, 0–1.
  final double? share;
  final PacingPace pace;
  final String reading;

  static PacingMilestone? fromJson(dynamic value) {
    if (value is! Map) return null;
    final json = asJson(value);
    return PacingMilestone(
      chapter: asString(json['chapter']),
      wordsIn: json['words_in'] is num ? asInt(json['words_in']) : null,
      share: json['share'] is num ? asDouble(json['share']) : null,
      pace: PacingPace.fromWire(asString(json['pace'])),
      reading: asString(json['reading']),
    );
  }
}

enum PacingConnection {
  tight,
  partial,
  loose;

  static PacingConnection fromWire(String value) => switch (value) {
        'tight' => tight,
        'loose' => loose,
        _ => partial,
      };
}

/// Whether the ending is tightly connected to the main plot.
class PacingResolution {
  const PacingResolution({required this.connection, required this.reading, required this.looseEnds});
  final PacingConnection connection;
  final String reading;
  final List<String> looseEnds;

  static PacingResolution? fromJson(dynamic value) {
    if (value is! Map) return null;
    final json = asJson(value);
    return PacingResolution(
      connection: PacingConnection.fromWire(asString(json['connection'])),
      reading: asString(json['reading']),
      looseEnds: asStringList(json['loose_ends']),
    );
  }
}

enum ExpectationStatus {
  met,
  subverted,
  notAddressed;

  static ExpectationStatus fromWire(String value) => switch (value) {
        'met' => met,
        'subverted' => subverted,
        _ => notAddressed,
      };
}

class GenreExpectation {
  const GenreExpectation({required this.expectation, required this.status, required this.how});
  final String expectation;
  final ExpectationStatus status;
  final String how;

  static GenreExpectation fromJson(Json json) => GenreExpectation(
        expectation: asString(json['expectation']),
        status: ExpectationStatus.fromWire(asString(json['status'])),
        how: asString(json['how']),
      );
}

class GenreEntry {
  const GenreEntry({required this.name, required this.primary, required this.why, required this.expectations});
  final String name;
  final bool primary;
  final String why;
  final List<GenreExpectation> expectations;

  static GenreEntry fromJson(Json json) => GenreEntry(
        name: asString(json['name']),
        primary: json['role'] == 'primary',
        why: asString(json['why']),
        expectations: asJsonList(json['expectations']).map(GenreExpectation.fromJson).toList(),
      );
}

/// One book analysis. Which of `themes`, the pacing fields (`beats`,
/// `reading`, `acts`) or `genres` is filled is `analysis`; the others come
/// back empty.
class AnalysisReport {
  const AnalysisReport({
    required this.analysis,
    required this.generatedAt,
    required this.chapterCount,
    required this.ranged,
    required this.overview,
    required this.themes,
    required this.beats,
    required this.reading,
    required this.acts,
    required this.genres,
  });
  final String analysis;
  final String generatedAt;
  final int chapterCount;

  /// Read over a range of chapters rather than the whole book.
  final bool ranged;
  final String overview;
  final List<ThemeEntry> themes;
  final List<PacingBeat> beats;
  /// Pacing: the book (or the chapters picked) read for engagement.
  final PacingReading reading;

  /// Pacing: each act read the same way; empty on a range.
  final List<PacingAct> acts;
  final List<GenreEntry> genres;

  static AnalysisReport fromJson(Json json) => AnalysisReport(
        analysis: asString(json['analysis']),
        generatedAt: asString(json['generated_at']),
        chapterCount: asInt(json['chapter_count']),
        ranged: json['range'] is Map,
        overview: asString(json['overview']),
        themes: asJsonList(json['themes']).map(ThemeEntry.fromJson).toList(),
        beats: asJsonList(json['beats']).map(PacingBeat.fromJson).toList(),
        reading: PacingReading.fromJson(json),
        acts: asJsonList(json['acts']).map(PacingAct.fromJson).toList(),
        genres: asJsonList(json['genres']).map(GenreEntry.fromJson).toList(),
      );
}

enum OutlineLength {
  synopsis,
  extended,
  detailed;

  String get wire => name;
}

/// One chapter of the detailed reverse outline. The entry carries more
/// (POV, interior track, relational beat); the page reads only these.
class ChapterOutline {
  const ChapterOutline({required this.chapter, required this.summary, required this.wordCount});
  final String chapter;
  final String summary;
  final int? wordCount;

  static ChapterOutline fromJson(Json json) => ChapterOutline(
        chapter: asString(json['chapter']),
        summary: asString(json['summary']),
        wordCount: json['word_count'] is num ? asInt(json['word_count']) : null,
      );
}

/// A synopsis or extended outline: continuous prose, setup to resolution,
/// with no section headers. [text] is paragraphs separated by a blank line.
class CondensedOutline {
  const CondensedOutline({required this.wordCount, required this.text});
  final int wordCount;
  final String text;

  static CondensedOutline fromJson(Json json) => CondensedOutline(
        wordCount: asInt(json['word_count']),
        text: asString(json['text']),
      );
}

/// Every length of the reverse outline, from the one cache row. `chapters`
/// is empty when the book has never been outlined.
class OutlineResult {
  const OutlineResult({required this.chapters, required this.synopsis, required this.extended});
  final List<ChapterOutline> chapters;
  final CondensedOutline? synopsis;
  final CondensedOutline? extended;

  static const empty = OutlineResult(chapters: [], synopsis: null, extended: null);

  CondensedOutline? condensed(OutlineLength length) => switch (length) {
        OutlineLength.synopsis => synopsis,
        OutlineLength.extended => extended,
        OutlineLength.detailed => null,
      };

  static OutlineResult fromJson(Json json) => OutlineResult(
        chapters: asJsonList(json['outline']).map(ChapterOutline.fromJson).toList(),
        synopsis: json['synopsis'] is Map ? CondensedOutline.fromJson(asJson(json['synopsis'])) : null,
        extended: json['extended'] is Map ? CondensedOutline.fromJson(asJson(json['extended'])) : null,
      );
}

/// How the author ruled on a finding: `prior` — the earlier chapter is
/// right; `current` — the newer one is; `intentional` — a deliberate change.
class ContinuityResolution {
  const ContinuityResolution({required this.choice, required this.note});
  final String choice;
  final String? note;

  static ContinuityResolution fromJson(Json json) =>
      ContinuityResolution(choice: asString(json['choice']), note: json['note'] as String?);
}

/// One finding. Every field but `chapter` is advisory on the wire, so each
/// is read defensively.
class ContinuityFinding {
  const ContinuityFinding({
    required this.hardError,
    required this.category,
    required this.entity,
    required this.chapter,
    required this.quote,
    required this.priorChapter,
    required this.priorQuote,
    required this.claim,
    required this.explanation,
    required this.verified,
    required this.resolution,
  });
  final bool hardError;
  final String category;
  final String? entity;
  final String chapter;
  final String? quote;
  final String? priorChapter;
  final String? priorQuote;
  final String? claim;
  final String? explanation;
  final bool verified;
  final ContinuityResolution? resolution;

  static String? _text(dynamic value) => value is String && value.trim().isNotEmpty ? value : null;

  static ContinuityFinding fromJson(Json json) => ContinuityFinding(
        hardError: json['kind'] != 'arc_drift',
        category: asString(json['category']),
        entity: _text(json['entity']),
        chapter: asString(json['chapter']),
        quote: _text(json['quote']),
        priorChapter: _text(json['prior_chapter']),
        priorQuote: _text(json['prior_quote']),
        claim: _text(json['claim']),
        explanation: _text(json['explanation']) ?? _text(json['why_not_development']),
        verified: asBool(json['verified'], true),
        resolution: json['resolution'] is Map ? ContinuityResolution.fromJson(asJson(json['resolution'])) : null,
      );
}

class ContinuityReport {
  const ContinuityReport({
    required this.chaptersAnalyzed,
    required this.hardErrors,
    required this.arcDrift,
    required this.claimsExtracted,
    required this.candidates,
    required this.dismissed,
    required this.extractionFailures,
  });
  final int chaptersAnalyzed;
  final List<ContinuityFinding> hardErrors;
  final List<ContinuityFinding> arcDrift;
  final int claimsExtracted;
  final int candidates;
  final int dismissed;
  final List<String> extractionFailures;

  static ContinuityReport fromJson(Json json) {
    final stats = json['stats'] is Map ? asJson(json['stats']) : const <String, dynamic>{};
    return ContinuityReport(
      chaptersAnalyzed: asInt(json['chapters_analyzed']),
      hardErrors: asJsonList(json['hard_errors']).map(ContinuityFinding.fromJson).toList(),
      arcDrift: asJsonList(json['arc_drift']).map(ContinuityFinding.fromJson).toList(),
      claimsExtracted: asInt(stats['claims_extracted']),
      candidates: asInt(stats['candidates']),
      dismissed: asInt(stats['dismissed']),
      extractionFailures: asStringList(stats['extraction_failures']),
    );
  }
}
